export type AnamnesisData = {
  id?: number;
  hasChronicDisease?: boolean | null;
  chronicDiseaseDescription?: string | null;
  usesContinuousMedication?: boolean | null;
  medicationDescription?: string | null;
  hasAllergies?: boolean | null;
  allergyDescription?: string | null;
  hadAestheticTreatment?: boolean | null;
  treatmentDescription?: string | null;
  hasTattoos?: boolean | null;
  usesAspirin?: boolean | null;
  hasKeloids?: boolean | null;
  hasVitiligo?: boolean | null;
  hasPsoriasis?: boolean | null;
  hasDepression?: boolean | null;
  depressionControlled?: boolean | null;
  hasAnemia?: boolean | null;
  hadCancer?: boolean | null;
  isPregnant?: boolean | null;
  isBreastfeeding?: boolean | null;
  hasDiabetes?: boolean | null;
  hasHypertension?: boolean | null;
  usesCorticosteroids?: boolean | null;
  usedRoacutan?: boolean | null;
  practicesPhysicalActivity?: boolean | null;
  activityDescription?: string | null;
  consumesAlcohol?: boolean | null;
  smokes?: boolean | null;
  usesHormonalContraceptive?: boolean | null;
  contraceptiveDescription?: string | null;
  hasFoodAllergy?: boolean | null;
  foodAllergyDescription?: string | null;
  notes?: string | null;
  createdAt?: string;
  updatedAt?: string;
};
